.github/workflows/cd-website.yml, website/astro.config.mjs, website/src/content/docs/index.mdx
Set up a CD pipeline to deploy the website to GitHub pages each time changes to the `website/` sub-directory are pushed to main.
- Fixes #6 
- Updated `website/astro.config.mjs` to work with GitHub pages
- Adds `.github/workflows/cd-website.yml` to set up automatic deploys
2. Run `npm run dev`
3. Go to http://localhost:4321/simpler-grants-protocol/ **Note:** the trailing `/` is important because it enables relative links to work correctly
> Screenshots, GIF demos, code examples or output to help show the …
=> [Issue #6] Publish website to GitHub pages

website/.cspell.json, website/astro.config.mjs, website/src/content/docs/decisions/adr/0004-specification-framework.md
Records ADR choosing TypeSpec as the specification framework.
- Fixes #7 
- Adds an ADR choosing TypeSpec as the specification format
- Adds "transpiles" to the cspell dictionary
2. Run `npm preview` from the root of the `website/` directory (with node 20.x installed)
3. Visit http://localhost:4321/simpler-grants-protocol/decisions/adr/0004-specification-framework/ to read the ADR
=> [Issue #7] Records ADR for specification framework

examples/custom-api/.gitignore, examples/custom-api/README.md, examples/custom-api/package-lock.json, examples/custom-api/package.json, examples/custom-api/src/main.tsp, examples/custom-api/src/models.tsp, examples/custom-api/src/routes.tsp, examples/custom-api/tspconfig.yaml, specs/.gitignore, specs/README.md, specs/lib/main.tsp, specs/lib/models/base.tsp, specs/lib/models/currency.tsp, specs/lib/models/custom-field.tsp, specs/lib/models/event.tsp, specs/lib/models/funding.tsp, specs/lib/models/index.tsp, specs/lib/models/opportunity.tsp, specs/lib/routes/index.tsp, specs/lib/routes/opportunities.tsp, specs/package-lock.json, specs/package.json, specs/src/index.ts, specs/src/lib.ts, specs/tsconfig.json, specs/tspconfig.yaml
Sets up `specs/` codebase
- Fixes #20 
- Adds `specs/` sub-directory with code for the first draft of the base specification library for the grant protocol
- Adds `examples/custom-api/` that demonstrates how to import and use that library to define a custom field and override the base routes
Follow the instructions in the two README files:
- `specs/README.md`
- `examples/custom-api/README.md`
Output of `npm run prepare:deps` from the …
=> [Issue #20] Set up `specs/` codebase

.github/workflows/cd-specs-npm.yml, .github/workflows/ci-specs-npm.yml, specs/README.md, specs/package-lock.json, specs/package.json
Creates a GitHub action to publish the `@common-grants/core` package to NPM via GitHub actions.
- Fixes #50
- Adds GitHub actions to publish the package to npm
- Updates the package README
Here's the [dry run of the publish](https://github.com/HHS/simpler-grants-protocol/actions/runs/12958709407/job/36149626793?pr=52).
=> [Issue #50]: Publish spec to npm via GitHub action

website/package-lock.json, website/src/content/docs/decisions/adr/0010-release-workflow.md
Documents an ADR to use a GitHub action-based CI/CD pipeline to publish prereleases to `npm` before our first stable release, with plans to migrate to Changesets afterward.
- Fixes #54 
Adds an ADR for our release workflow.
2. Change directory into `website/`
3. Run `npm run dev`
=> [Issue #54] ADR for release strategy

specs/README.md, specs/lib/main.tsp, specs/lib/models/custom-enum.tsp, specs/lib/models/custom-field.tsp, specs/lib/models/event.tsp, specs/lib/models/index.tsp, specs/lib/models/metadata.tsp, specs/lib/models/money.tsp, specs/lib/models/opportunity/base.tsp, specs/lib/models/opportunity/funding.tsp, specs/lib/models/opportunity/index.tsp, specs/lib/models/opportunity/status.tsp, specs/lib/models/opportunity/timeline.tsp, specs/lib/responses/errors.tsp, specs/lib/responses/success.tsp, specs/lib/routes/opportunities.tsp, specs/package-lock.json, specs/package.json
Updates the data models in the `v0.1.0-alpha` version of the CommonGrants TypeSpec library
- Fixes #22 
- Time to review: [xx] minutes
- Adds the following models:
- `SystemMetadata` which can be spread into other models to include `createdAt` and `lastModifiedAt`
- `OppTimeline` which updates how key dates in the opportunity timeline are represented
- `CustomEnumValue` which provides a flexible way of extending default enum values
- Reorganizes the models related to `Opportunity`
- Improves docstrings for the models in the package
- Updates `Opportunity` model in the following ways:
- Removes templating -- that just added complexity
- Adds a `status` property
- Adds a `keyDates` property
> Testing instructions, background context, more …
=> [Issue #22] Update data models

templates/README.md, templates/custom-api/main.tsp, templates/custom-api/models.tsp, templates/custom-api/routes.tsp, templates/custom-api/tspconfig.yaml, templates/default-api/main.tsp, templates/default-api/tspconfig.yaml, templates/template.json
Adds a series of TypeSpec templates that we can use for the `cg init` function.
- Supports #63 
Creates a `templates/` directory with scaffolding for the following templates:
- Default CommonGrants API
- CommonGrants API with custom fields
1. With `@typespec/compiler` installed globally, open a new directory and run the following command:
```
tsp init https://raw.githubusercontent.com/HHS/simpler-grants-protocol/9c829a2afe9a8a561d42967e8089656cb2459844/templates/template.json
```
2. Follow the prompts to set up your project
3. …
=> [Issue #63] TypeSpec templates

cli/README.md, cli/package-lock.json, cli/package.json, cli/src/__tests__/commands/init.test.ts, cli/src/__tests__/services/init.service.test.ts, cli/src/commands/init.ts, cli/src/services/init.service.ts, cli/src/services/interfaces.ts, cli/src/types/command-args.ts
Implements the `cg init` command for the CLI.
- Fixes #63 
- Implements the `cg init` command to call `tsp init` under the hood
- Updates the `--list` flag to read template options directly from the hosted template JSON
- Removes `--dir` as an option for the command since `tsp init` doesn't currently support custom output directories
The easiest way to test this is:
2. Run `npm build && npm link`
3. In a separate directory (empty) run `npm link @common-grants/cli`
4. Create a test directory and change …
=> [Issue #63] Implement `cg init` command

cli/README.md, cli/package-lock.json, cli/package.json, cli/src/__tests__/commands/compile.test.ts, cli/src/__tests__/commands/error-handling.test.ts, cli/src/__tests__/commands/preview.test.ts, cli/src/__tests__/fixtures/invalid.yaml, cli/src/__tests__/fixtures/valid.json, cli/src/__tests__/fixtures/valid.yaml, cli/src/__tests__/services/compile.service.test.ts, cli/src/__tests__/services/init.service.test.ts, cli/src/__tests__/services/preview.service.test.ts, cli/src/commands/compile.ts, cli/src/commands/preview.ts, cli/src/index.ts, cli/src/services/compile.service.ts, cli/src/services/init.service.ts, cli/src/services/interfaces.ts, cli/src/services/preview.service.ts, cli/src/types/command-args.ts, cli/src/utils/typespec.ts, cli/tsconfig.json
Implements `cg preview` and adds `cg compile` command.
- Fixes #64 
- Implements `cg preview` and drops support (temporarily) for files ending in `.tsp` and the `--ui` option
- Implements `cg compile`
- Updates `cli/README.md`
2. Run `npm run build && npm link` to link the package locally
3. In a separate, empty directory run `npm link @common-grants/cli`
4. Run `cg init --template default-api` and complete the prompts with `Default` as the namespace
5. Run `cg compile main.tsp` to compile the …
=> [Issue #64] preview command

cli/package-lock.json, cli/package.json, cli/src/utils/typespec.ts, templates/template.json
Fixes how the path `tsp` CLI is resolved in the CommonGrants CLI, so that `cg init` and `cg compile` can serve as thin-wrappers for `tsp init` and `tsp compile`
- Relates to #40 
- Time to review: [xx] minutes
- Adds `@typespec/compiler` as a direct dependency
- Changes how we resolve the path to the `tsp` binary
- Adds back the `default-api` template
2. Change directory into the `cli/`: `cd cli`
3. Run `npm pack`
4. In a separate clean directory install the tarball: `npm install <path-to-tarball>`
5. Run `npx cg init`
=> [Issue #40] Fix CLI dependencies

.github/workflows/ci-specs-npm.yml, specs/README.md, specs/package-lock.json, specs/package.json, specs/scripts/prepublish-checks.sh, templates/custom-api/routes.tsp, templates/default-api/main.tsp, templates/quickstart/routes.tsp, website/src/content/docs/getting-started.mdx
Updates templates and bumps the `@common-grants/core` prerelease version
- Relates to #87 
- Adds a `prepublishOnly` check that fails if the current version matches the published version
- Adds the `POST /common-grants/opportunities/search` route to each of the templates
- Adds the `POST /common-grants/opportunities/search` route to the README and quickstart guide
=> [Issue 87] Bump `@common-grants/core` prerelease version

templates/express-js/package-lock.json, website/.cspell.json, website/package-lock.json, website/src/content/docs/governance/adr/0017-mapping-format.md
Publishes an ADR documenting the recommendation to use a custom JSON mapping format to translate data from platform-specific schemas to CommonGrants models.
- Fixes #184 
- Adds Mapping format ADR
- Fixes vulnerability in the website dependencies
- Fixes vulnerability in the Express JS template
2. From the root of the `website/` directory run: `npm run preview`
3. Go to: http://localhost:4321/governance/adr/0017-mapping-format/
> Screenshots, GIF demos, code examples or output to help show the changes …
=> [Issue #184] ADR for mapping format

website/astro.config.mjs
Adds Cabin analytics to track site traffic and usage. Cabin is a low-carbon alternative to Google Analytics that doesn't require cookies or collect IP addresses.
- Related to #175 
Adds Cabin script to header in `astro.config.js` for the website
This is hard to test until we deploy it.
=> [Issue #175] Add Cabin analytics

website/src/content/docs/governance/adr/0018-apply-endpoints.md
- Fixes #195 
Adds ADR documenting the choice to define two sets of endpoints to 1) support third-party submissions for platform-defined forms, 2) to map those forms to a common data model and support form prefills.
2. Run `npm run preview` from the root of the `website/` sub-directory
3. Go to: http://localhost:4321/governance/adr/0018-apply-endpoints/
=> [Issue #195] ADR for apply routes

lib/cli/package.json, pnpm-lock.yaml
- Fixes #233 
Update CLI dependency on Core, from `^0.1.0` to `0.1.0` (i.e. removed carat prefix). The downstream effect is that when `changeset version` applies a new version number to Core, it will also automatically bump the CLI dependency and version.
=> [Issue #233] Update CLI version when Core version changes

.github/workflows/ci-lib-core.yml, lib/core/lib/api.tsp, lib/core/lib/core/fields/custom-field.tsp, lib/core/lib/core/fields/file.tsp, lib/core/lib/core/fields/index.tsp, lib/core/lib/core/models/application.tsp, lib/core/lib/core/models/competition.tsp, lib/core/lib/core/models/form-response.tsp, lib/core/lib/core/models/form.tsp, lib/core/lib/core/models/index.tsp, lib/core/lib/core/models/mapping.tsp, lib/core/lib/core/models/proposal.tsp, lib/core/lib/core/responses/success.tsp, lib/core/lib/core/routes/applications.tsp, lib/core/lib/core/routes/competitions.tsp, lib/core/lib/core/routes/form-responses.tsp, lib/core/lib/core/routes/index.tsp, lib/core/lib/main.tsp, lib/core/package.json, lib/core/tspconfig.yaml, package-lock.json, pnpm-lock.yaml
- Fixes #167 
- Fixes #166 
- Fixes #163 
- Adds experimental tag to API
- Adds or updates the following models to support applications:
- Competition
- Application (updated)
- Form
- FormResponse
- Proposal (re-uses content formerly in Application)
- Mapping
- Adds the following experimental endpoints:
- Direct apply workflow
- `GET /competitions/<id>` View competition details
- `POST /competitions/<id>/apply/` Apply to a competition
- Multi-step apply workflow (what Simpler.Grants.gov is prioritizing)
- `POST /applications/start/` Start an application
- `GET /applications/<id>` View an application
- `PUT /applications/<appId>/forms/<formId>` Respond to a form
- `GET /applications/<appId>/forms/<formId>` Get a …
=> [Issue #167] Add apply models and routes

.changeset/khaki-years-sort.md, lib/core/lib/api.tsp, lib/core/lib/core/fields/address.tsp, lib/core/lib/core/fields/email.tsp, lib/core/lib/core/fields/file.tsp, lib/core/lib/core/fields/name.tsp, lib/core/lib/core/fields/pcs.tsp, lib/core/lib/core/models/applicant-type.tsp, lib/core/lib/core/models/application.tsp, lib/core/lib/core/models/competition.tsp, lib/core/lib/core/models/form-response.tsp, lib/core/lib/core/models/form.tsp, lib/core/lib/core/models/mapping.tsp, lib/core/lib/core/models/opportunity/base.tsp, lib/core/lib/core/models/organization.tsp, lib/core/lib/core/models/person.tsp, lib/core/lib/core/models/proposal.tsp, lib/core/lib/core/responses/error.tsp, lib/core/lib/core/types.tsp, lib/core/tspconfig.yaml, package-lock.json
Adds missing version decorators to routes, schemas, and properties introduced in v0.2.0 so that they are omitted from the v0.1.0 OpenAPI spec.
- Fixes #249 
- Adds `Versioning.added(CommonGrants.Versions.v0_2)` to all new routes, models, and fields
- Updates `tspconfig.yaml` to omit unreachable types
- Adds a PATCH changeset
2. Change directory to `lib/core`: `cd lib/core`
3. Run `npm run typespec` to generate the OpenAPI specs
4. Run `diff tsp-output/@typespec/openapi3/openapi.0.1.0.yaml …
=> [Issue #249] Fix versioning decorators in core library

website/src/components/SchemaFormatTabs.astro, website/src/content/docs/protocol/filters/date.mdx, website/src/content/docs/protocol/filters/money.mdx, website/src/content/docs/protocol/filters/numeric.mdx, website/src/content/docs/protocol/filters/string.mdx
- Fixes #291 
- Time to review: 3 minutes
This PR:
- Extends `<SchemaFormatTabs>` component to include links to source files 
- The JSON Schema tab links out to corresponding schema on https://commongrants.org
- The TypeSpec and Python tabs link out to corresponding source file on GitHub
- Corrects python file line numbers for a handful of filter schemas 
=> [Issue #291] Website - Extend schema tab component to include links to source files

website/astro.config.mjs, website/src/components/NavMenuItem.astro, website/src/components/starlight-overrides/Header.astro, website/src/components/starlight-overrides/PageFrame.astro
Add links to the navbar so folks can access docs from the landing page without first clicking on "Read docs" 
- Fixes #261 
- Overrides default [`PageFrame` component](https://github.com/withastro/starlight/blob/main/packages/starlight/components/PageFrame.astro) to expose `MobileMenuToggle` on pages with the "splash" template (i.e. the landing page)
- Adds a `NavMenuItem` component
- Updates the existing `Header` override component to include `NavMenuItem`
- Resizes the `Search` component to fit the `NavMenuItem`
There might …
=> [Issue #261] Add links to navbar

.github/ISSUE_TEMPLATE/5-internal-coplanning.md
Issue template didn't render correctly because I had the wrong key in the frontmatter. It needs to be `about` instead of `description`
- Fixes #312 
- Time to review: 1 minute
Changes frontmatter key from `description` to `about`
N/A
=> [Issue #312] Fix co-planning issue template
