HHS/simpler-grants-protocol

.github/ISSUE_TEMPLATE/3-internal-decision.yml, website/astro.config.mjs, website/src/content/docs/decisions/adr-template.md, website/src/content/docs/decisions/adr/0001-using-adrs.md, website/src/content/docs/decisions/adr/adr-template.md, website/src/content/docs/decisions/overview.md
- Fixes #10 
- Adds a new section of the website for decision records
- Adds an overview about ADRs
- Adds an ADR to record the decision to use ADRs
- Updates the Internal - Decision issue template to reference the ADR location
2. Run `npm run build && npm run preview` from the root of the `website/` subdirectory
3. Go to: http://localhost:4321/simpler-grants-protocol/decisions/overview
The ADR template should be …
=> [Issue #10] ADR template

website/.cspell.json, website/src/content/docs/decisions/adr/0005-protocol-scope.md, website/src/content/docs/decisions/adr/0006-protocol-compliance.md, website/src/content/docs/decisions/adr/0007-initial-models-and-routes.md, website/src/content/docs/decisions/adr/0008-custom-fields.md, website/src/content/docs/decisions/adr/0009-monetary-fields.md
Documents answers to open questions about the specification design.
- Fixes #18 
- Time to review: 15 minutes
Documents answers to:
- The inspiration and scope of the protocol
- The definition of "compliance" with the protocol base spec
- Which models and routes we'll aim to include in v0.1.0 of the protocol
- The mechanism for defining custom fields
- The format for representing monetary values
2. Change directory to the `website/` codebase: `cd website`
3. Build the docs: `npm run dev`
> Screenshots, GIF demos, code examples or output …
=> [Issue #18] Answers specification design questions

website/src/content/docs/decisions/adr/0007-initial-models-and-routes.md, website/src/content/docs/decisions/adr/0009-monetary-fields.md
- Related to #18
Fixes some typos in a few ADRs.
=> [Issue #18] Updates research question ADRs

README.md, examples/README.md, examples/custom-api/README.md, examples/custom-api/package-lock.json, examples/custom-api/package.json, examples/custom-api/src/models.tsp, examples/custom-api/src/routes.tsp, specs/README.md, specs/lib/main.tsp, specs/lib/models/base.tsp, specs/lib/models/currency.tsp, specs/lib/models/custom-field.tsp, specs/lib/models/event.tsp, specs/lib/models/funding.tsp, specs/lib/models/index.tsp, specs/lib/models/opportunity.tsp, specs/lib/routes/index.tsp, specs/lib/routes/opportunities.tsp, specs/package-lock.json, specs/package.json, specs/src/lib.ts
Updates the repository to adopt the working title for the protocol: "CommonGrants"
- Fixes #31 
- Updates the TypeSpec library and example API to use `CommonGrants` instead of `OpportunityStream`
- Updates and expands the READMEs to link to these sections of the codebase
A lot of files were changed but the changes themselves are relatively minor.
=> [Issue #31] Update repo with working title

website/.cspell.json, website/.gitignore, website/astro.config.mjs, website/package-lock.json, website/package.json, website/src/content/docs/decisions/adr/0008-custom-fields.md, website/src/content/docs/decisions/adr/0009-monetary-fields.md, website/src/specs/main.tsp
Uses the `starlight-openapi` plugin to render the CommonGrants base API spec in the docs website.
- Fixes #55 
- Adds `@common-grants/core` to website dependencies
- Adds `starlight-openapi` to website dependencies
- Adds a `main.tsp` for the base CommonGrants API
- Configures the website to display the OpenAPI spec generated from `main.tsp`
2. Change directory into `website/`: `cd website`
3. Install new dependencies `npm install`
4. Build the website: `npm run dev`
5. Go to …
=> [Issue #55] API spec docs

.github/workflows/cd-cli-npm.yml, .github/workflows/ci-cli-npm.yml, cli/package.json
Adds missing script to CLI package.json
- Fixes #30 
- Time to review: 1 minute
=> [Issue 30] Fix error in CLI publish CI/CD

website/.prettierignore, website/astro.config.mjs, website/src/content/docs/reference/models/base-types.mdx, website/src/content/docs/reference/models/custom-field.mdx, website/src/content/docs/reference/models/event.mdx, website/src/content/docs/reference/models/metadata.mdx, website/src/content/docs/reference/models/money.mdx, website/src/content/docs/reference/models/opp-funding.mdx, website/src/content/docs/reference/models/opp-status.mdx, website/src/content/docs/reference/models/opp-timeline.mdx, website/src/content/docs/reference/models/opportunity-base.mdx, website/src/content/docs/reference/models/opportunity.mdx, website/src/content/docs/reference/models/overview.mdx
Documents the models in the core library.
- Fixes #73 
- Adds a new "Models" section to the reference portion of the docs
- Creates a page for each model in the `@common-grants/core` library with the following content:
- Table describing model properties
- JSON schema of the model
- TypeSpec code for the model
- Example of the model
1. Check out the PR locally
2. Change directory into website: `cd website`
3. Serve the website: `npm run dev`
> Screenshots, GIF demos, code examples or output to help show the changes working as …
=> [Issue #73] Core library docs

website/.cspell.json, website/src/content/docs/decisions/adr/0011-rfc-format.md, website/src/content/docs/getting-started.mdx, website/src/content/docs/reference/models/custom-field.mdx
- Fixes #35 
- Added an ADR for the RFC process
- Fixed a few typos on other pages
- Quickstart guide
- Custom field model
2. Change directory to website: `cd website`
3. Run: `npm run dev`
4. Go to: http://localhost:4321/simpler-grants-protocol/decisions/adr/0011-rfc-format/
=> [Issue #35] RFC planning ADR

templates/custom-api/main.tsp, templates/custom-api/models.tsp, templates/custom-api/routes.tsp, templates/default-api/main.tsp, templates/template.json, website/src/content/docs/getting-started.mdx
Update the quickstart guide and templates to match the updated library
- Fixes #88 
- Updates the templates
- Updates the quickstart guide
=> [Issue #88] Update quickstart guide and templates

website/src/content/docs/getting-started.mdx, website/src/content/docs/protocol/specification.md
Adds a "filtering" section to the specification
- Fixes #91 
- Time to review: 7 minutes
- Adds "Filtering" under the "Routes and operations" section
- Adds "Custom filters" under the "Extensions" section
- Improves guidance on first few steps of Quickstart guide
2. Run `npm run dev`
3. Go to: http://localhost:4321/simpler-grants-protocol/protocol/specification#filtering
=> [Issue #91]: Adds filtering section to specification

website/src/content/docs/getting-started.mdx
Updates the quickstart guide for usability tests
- Fixes #38 
Updates the quickstart guide
=> [Issue #38] Update quickstart guide for usability tests

examples/custom-api/package-lock.json, templates/express-js/package-lock.json, website/astro.config.mjs, website/package-lock.json, website/package.json
Fixes dependabot warnings in `website/`, `examples/custom-api`, and `templates/express-js`
- Fixes dependabot issues
- Fixes missing links in website sidebar
- Fixes styling issue with latest Astro version
=> Fix: Dependabot warning

website/astro.config.mjs, website/src/content/docs/about.mdx, website/src/content/docs/decisions/adr/0001-using-adrs.md, website/src/content/docs/getting-started.mdx, website/src/content/docs/index.mdx, website/src/content/docs/protocol/fields/custom-field.mdx, website/src/content/docs/protocol/fields/event.mdx, website/src/content/docs/protocol/fields/index.md, website/src/content/docs/protocol/fields/metadata.mdx, website/src/content/docs/protocol/fields/money.mdx, website/src/content/docs/protocol/filters/date.mdx, website/src/content/docs/protocol/filters/index.md, website/src/content/docs/protocol/filters/money.mdx, website/src/content/docs/protocol/filters/numeric.mdx, website/src/content/docs/protocol/filters/string.mdx, website/src/content/docs/protocol/models/index.md, website/src/content/docs/protocol/models/opp-base.mdx, website/src/content/docs/protocol/models/opp-funding.mdx, website/src/content/docs/protocol/models/opp-status.mdx, website/src/content/docs/protocol/models/opp-timeline.mdx, website/src/content/docs/protocol/overview.mdx, website/src/content/docs/protocol/sorting.mdx, website/src/content/docs/protocol/specification.md, website/src/content/docs/protocol/types/index.md
- Fixes #33 
- Removes base path
- Updates relative links
There is an extra step happening behind the scenes where we need to set up a custom domain.
You can see a fully functional site at the following domain: https://commongrants.billydaly.dev/
=> [Issue #33] Update site URL

website/src/content/docs/decisions/adr-template.md, website/src/content/docs/decisions/adr/0001-using-adrs.md, website/src/content/docs/decisions/adr/0002-website-framework.md, website/src/content/docs/decisions/adr/0003-website-hosting.md, website/src/content/docs/decisions/adr/0004-specification-framework.md, website/src/content/docs/decisions/adr/0005-protocol-scope.md, website/src/content/docs/decisions/adr/0006-protocol-compliance.md, website/src/content/docs/decisions/adr/0007-initial-models-and-routes.md, website/src/content/docs/decisions/adr/0008-custom-fields.md, website/src/content/docs/decisions/adr/0009-monetary-fields.md, website/src/content/docs/decisions/adr/0010-release-workflow.md, website/src/content/docs/decisions/adr/0011-pagination.md, website/src/content/docs/decisions/adr/0012-filtering.md, website/src/content/docs/decisions/adr/0013-sorting.md, website/src/content/docs/decisions/adr/0014-custom-routes.md, website/src/content/docs/decisions/adr/0015-rfc-format.md, website/src/content/docs/decisions/adr/0016-governance-model.md
Updates ADR format and records an ADR for the proposed governance model.
- Fixes #114 
- Updates ADR format
- Adds an ADR for the governance model
2. Change directory into `website`: `cd website`
3. Run `npm run preview`
4. Go to http://localhost:4321/decisions/adr/0016-governance-model/
New format
Governance ADR
=> [Issue #114] ADR for governance model

cli/package-lock.json, cli/package.json, examples/custom-api/package-lock.json, examples/custom-api/package.json, examples/custom-api/src/main.tsp, templates/express-js/package-lock.json, templates/express-js/package.json, templates/express-js/src/typespec/main.tsp
Updates examples and templates to use the latest `@common-grants/core` library
- Extends #85 
- Bumps `examples/custom-api` to use the latest library
- Bumps `templates/express-js` to use the latest library
- Bumps `@common-grants/cli` to use the latest library and compiler
=> [Issue #85] Update CLI, examples, and templates

website/src/content/docs/getting-started.mdx
Incorporates some quick fixes from the usability test sessions conducted today.
- Fixes #105 
- Time to review: 1 minute
- Adds prerequisite tool tip for the quickstart guide
- Fixes link to TypeSpec docs
=> [Issue #105] Usability test quick fixes

website/astro.config.mjs, website/src/content/docs/protocol/fields/custom-field.mdx, website/src/content/docs/protocol/fields/event.mdx, website/src/content/docs/protocol/fields/metadata.mdx, website/src/content/docs/protocol/fields/money.mdx, website/src/content/docs/protocol/filters/base.mdx, website/src/content/docs/protocol/filters/date.mdx, website/src/content/docs/protocol/filters/money.mdx, website/src/content/docs/protocol/filters/numeric.mdx, website/src/content/docs/protocol/filters/string.mdx, website/src/content/docs/protocol/models/opp-base.mdx, website/src/content/docs/protocol/models/opp-funding.mdx, website/src/content/docs/protocol/models/opp-status.mdx, website/src/content/docs/protocol/models/opp-timeline.mdx, website/src/content/docs/protocol/pagination.mdx, website/src/content/docs/protocol/sorting.mdx, website/src/content/docs/protocol/types/date.mdx, website/src/content/docs/protocol/types/numeric.mdx, website/src/content/docs/protocol/types/other.mdx, website/src/content/docs/protocol/types/string.mdx
Updates the protocol reference section based on user feedback.
- Fixes #125 
- Pulls table out of the tabs on each protocol reference page
- Standardizes the order, content, and naming of the reference tabs
- Fixes other small typos and discrepancies
2. Run `npm run preview` from the root of the website directory
3. Go to: http://localhost:4321/
=> [Issue #125] Update protocol reference section

website/package-lock.json, website/package.json, website/public/openapi.yaml, website/src/content/docs/protocol/pagination.mdx, website/src/content/docs/protocol/responses/filtered.mdx, website/src/content/docs/protocol/responses/paginated.mdx, website/src/content/docs/protocol/responses/sorted.mdx, website/src/content/docs/protocol/sorting.mdx, website/src/content/docs/protocol/specification.md
Updates the website to the latest dependencies for `astro` and `@common-grants/core` and makes some other small fixes to formatting.
- Fixes #108 
- Bumps `astro` to latest version
- Bumps `@common-grants/core` to latest alpha version
- Updates Appendix A in the specification
- Updates name of `PaginationInfo` and `SortInfo` in protocol reference pages to reflect latest core library updates
1. Checkout the PR locally:
2. Run the following from the root of `website`: `npm run preview`
3. Go to …
=> [Issue #108] Update website dependencies

website/astro.config.mjs, website/package-lock.json, website/package.json
- Fixes #174
- Updates Vite to address vulnerability
- Updates to latest Starlight version to get access to anchor links in headers
- Fixes the social link (i.e. GitHub) configuration in `astro.config.js`
2. Change directory to website: `cd website`
3. Preview the site: `npm run preview`
=> [Issue #174] Add anchor links to website headings

website/.cspell.json, website/astro.config.mjs, website/src/components/Header.astro
- Fixes #202 
- Overrides default header component
- Adds CTA button to the new component
=> [Issue #202] Add interest form to navbar

cli/.gitignore, cli/.prettierignore, cli/lib/openapi.yaml, cli/package-lock.json, cli/package.json, cli/src/__tests__/commands/check/check-args.test.ts, cli/src/__tests__/commands/check/check-service.test.ts, cli/src/__tests__/commands/check/utils/check-extra-routes.test.ts, cli/src/__tests__/commands/check/utils/check-matching-routes.test.ts, cli/src/__tests__/commands/check/utils/check-missing-routes.test.ts, cli/src/__tests__/commands/check/utils/check-schema-compatibility.test.ts, cli/src/__tests__/commands/check/utils/error-utils.test.ts, cli/src/commands/check/README.md, cli/src/commands/check/check-args.ts, cli/src/commands/check/check-service.ts, cli/src/commands/check/utils/check-extra-routes.ts, cli/src/commands/check/utils/check-matching-routes.ts, cli/src/commands/check/utils/check-missing-routes.ts, cli/src/commands/check/utils/check-schema-compatibility.ts, cli/src/commands/check/utils/error-utils.ts, cli/src/commands/check/utils/types.ts
- Fixes #152 
- Added new error handlers:
- `ErrorCollection` to store and manipulate a collection of errors
- `ErrorFormatter` to format and print an error collection to the console
- Updated the `src/commands/check/utils` modules to use these new error handlers
- Added a `src/commands/check/README.md` explaining the validation cases we expect to handle
- Fixed a dependency vulnerability
- Switched to using an OpenAPI spec directly included in the package instead of generating one to avoid difficult to diagnose compilation errors when the package was installed globally
> Testing instructions, background context, more in-depth details of the implementation, and anything else you'd like to call out or ask …
=> [Issue #152] Improve check spec output

.github/workflows/ci-template-fast-api-check-spec.yml, lib/python-sdk/common_grants_sdk/schemas/fields.py, lib/python-sdk/common_grants_sdk/schemas/models/opp_base.py, lib/python-sdk/common_grants_sdk/schemas/models/opp_funding.py, lib/python-sdk/common_grants_sdk/schemas/models/opp_status.py, lib/python-sdk/common_grants_sdk/schemas/models/opp_timeline.py, lib/python-sdk/tests/schemas/test_opportunity.py, templates/fast-api/Makefile, templates/fast-api/src/common_grants/routes/opportunities.py, templates/fast-api/src/common_grants/schemas/__init__.py, templates/fast-api/src/common_grants/schemas/filters/money_filters.py, templates/fast-api/src/common_grants/schemas/models/__init__.py, templates/fast-api/src/common_grants/schemas/models/opp_search.py, templates/fast-api/src/common_grants/schemas/models/opp_search_request.py, templates/fast-api/src/common_grants/schemas/pagination.py, templates/fast-api/src/common_grants/schemas/response.py, templates/fast-api/src/common_grants/schemas/sorting.py, templates/fast-api/src/common_grants/scripts/generate_openapi.py, templates/fast-api/src/common_grants/services/opportunity.py, templates/fast-api/src/common_grants/services/utils.py, templates/fast-api/tests/common_grants/routes/test_opportunities.py, templates/fast-api/tests/common_grants/schemas/fields/test_fields.py, templates/fast-api/tests/common_grants/schemas/models/test_opp_base.py, templates/fast-api/tests/common_grants/schemas/models/test_opp_funding.py, templates/fast-api/tests/common_grants/schemas/models/test_opp_status.py, templates/fast-api/tests/common_grants/schemas/models/test_opp_timeline.py, templates/fast-api/tests/common_grants/schemas/test_filters.py, templates/fast-api/tests/common_grants/schemas/test_opportunity.py, templates/fast-api/tests/conftest.py
- Fixes #156 
Multiple updates to FastAPI template to make it compliant with base spec.
BEFORE:
AFTER:
=> [Issue 156] Update FastAPI template to pass check spec

website/src/content/docs/protocol/fields/address.mdx, website/src/content/docs/protocol/fields/custom-field.mdx, website/src/content/docs/protocol/fields/email.mdx, website/src/content/docs/protocol/fields/event.mdx, website/src/content/docs/protocol/fields/metadata.mdx, website/src/content/docs/protocol/fields/money.mdx, website/src/content/docs/protocol/fields/name.mdx, website/src/content/docs/protocol/fields/pcs.mdx, website/src/content/docs/protocol/fields/phone.mdx, website/src/content/docs/protocol/filters/base.mdx, website/src/content/docs/protocol/filters/date.mdx, website/src/content/docs/protocol/filters/money.mdx, website/src/content/docs/protocol/filters/numeric.mdx, website/src/content/docs/protocol/filters/string.mdx, website/src/content/docs/protocol/models/application.mdx, website/src/content/docs/protocol/models/opportunity.mdx, website/src/content/docs/protocol/models/organization.mdx, website/src/content/docs/protocol/models/person.mdx, website/src/content/docs/protocol/pagination.mdx, website/src/content/docs/protocol/responses/error.mdx, website/src/content/docs/protocol/responses/filtered.mdx, website/src/content/docs/protocol/responses/paginated.mdx, website/src/content/docs/protocol/responses/sorted.mdx, website/src/content/docs/protocol/responses/success.mdx, website/src/content/docs/protocol/sorting.mdx, website/src/content/docs/protocol/types/date.mdx, website/src/content/docs/protocol/types/numeric.mdx, website/src/content/docs/protocol/types/string.mdx
Updates paths to core library in website documentation after relocating the core library to `lib/core/`
- Relates to #216 
Updates paths to the TypeSpec section of the `SchemaFormatTabs` components after moving the core library to `lib/core/`
We'll need to update at least some file ranges after we make changes to the contents of the core library in #162 for the v0.1.0 release.
=> [Issue #216] Update website docs part 1

.changeset/green-pigs-love.md, .github/workflows/ci-package-bump-version.yml, lib/core/CHANGELOG.md, lib/core/package.json, pnpm-lock.yaml
Fixes CI/CD failure in the `bump-package-versions.yaml` from previous merge to main.
- Fixes #222 
- Reverts previous commit on main
- Changed working directory for bump python version step
- Skipped python tags step if python version wasn't bumped
- Runs tag steps on pull requests
=> [Issue #222] Fast follow release workflow

.github/workflows/cd-lib-core-publish.yml
Remove --dry-run from `cd-lib-core-publish.yaml`
- Fixes #162 
=> [Issue #162] Publish core library to npm

.github/workflows/cd-deploy-lib-cli.yml, .github/workflows/cd-deploy-lib-core.yml
- Fixes #234 
Replaces CLI's deprecated publish-alpha workflow with new release-and-deploy workflow, following pattern set by Core release-and-deploy workflow. 
=> [Issue 234] Update CLI deploy workflow

lib/python-sdk/README.md, package-lock.json, templates/fast-api/README.md, templates/fast-api/src/common_grants/schemas/response.py, templates/fast-api/src/common_grants/services/opportunity.py, website/package-lock.json, website/src/content/docs/protocol/fields/custom-field.mdx, website/src/content/docs/protocol/fields/event.mdx, website/src/content/docs/protocol/fields/metadata.mdx, website/src/content/docs/protocol/fields/money.mdx, website/src/content/docs/protocol/filters/base.mdx, website/src/content/docs/protocol/filters/date.mdx, website/src/content/docs/protocol/filters/money.mdx, website/src/content/docs/protocol/filters/string.mdx, website/src/content/docs/protocol/models/opportunity.mdx, website/src/content/docs/protocol/pagination.mdx, website/src/content/docs/protocol/responses/filtered.mdx, website/src/content/docs/protocol/responses/paginated.mdx, website/src/content/docs/protocol/responses/sorted.mdx, website/src/content/docs/protocol/responses/success.mdx, website/src/content/docs/protocol/sorting.mdx
- Fixes #215 
This PR updates
* Website *.mdx files
* Python SDK README
* FastAPI Template README
The python documentation is stale. This PR freshens it up a bit.
=> [Issue #215] Documentation: Update Python examples

.changeset/giant-donuts-stick.md, lib/core/README.md, lib/core/lib/api.tsp, lib/core/lib/core/models/applicant-type.tsp, lib/core/lib/core/models/application.tsp, lib/core/lib/core/models/competition.tsp, lib/core/lib/core/models/form-response.tsp, lib/core/lib/core/models/form.tsp, lib/core/lib/core/models/index.tsp, lib/core/lib/core/models/mapping.tsp, lib/core/lib/core/models/opportunity/base.tsp, lib/core/lib/core/models/opportunity/status.tsp, lib/core/lib/core/responses/error.tsp, lib/core/lib/core/routes/applications.tsp, lib/core/lib/core/routes/competitions.tsp, lib/core/lib/core/routes/form-responses.tsp, lib/core/lib/core/routes/forms.tsp, lib/core/lib/core/routes/index.tsp, lib/core/lib/core/routes/opportunities.tsp, package-lock.json
- Relates to #249 
- Standardizes path params across routes
- Removes `POST /common-grants/competitions/{compId}/apply`
- Moves `GET /common-grants/competitions/{compId}` to separate tag
- Adds forms endpoints:
- `GET /common-grants/forms` List forms
- `GET /common-grants/forms/{formId}` View form details
- Adds `ApplicantType` model
- Makes changes to apply-related models: TODO list changes
1. Checkout PR locally
2. Run `npm ci` from the root of `lib/core/` (to ensure that dependencies are installed locally)
3. Run `npm run …
=> [Issue #249] Update core library

.github/workflows/cd-deploy-lib-pysdk.yml, package-lock.json, pnpm-lock.yaml
- Fixes #276 
- Update deploy workflow: 
- remove `dry-run` flag from `poetry publish` command 
- set GitHub Actions environment to enable PyPI integration
=> [Issue #276] PySDK: Remove dry-run flag from deploy workflow

lib/cli/DEVELOPMENT.md, lib/core/DEVELOPMENT.md, lib/python-sdk/DEVELOPMENT.md, templates/express-js/DEVELOPMENT.md, templates/fast-api/DEVELOPMENT.md, templates/quickstart/DEVELOPMENT.md
Create a series of linked release runbooks that show the steps to take to update each section of the codebase when a new version of the core library is updated.
- Fixes #265 
- Time to review: 7 minutes
- Adds new `DEVELOPMENT.md` files to the following sections of the codebase:
- `lib/core/`
- `lib/cli/`
- `templates/quickstart/`
- `templates/express-js/`
- `templates/fast-api/`
- Adds a release runbook to each of these development guides.
It's probably easiest to review the rendered version of each development guide.
> Screenshots, GIF demos, code …
=> [Issue #265] Create release runbooks

lib/core/lib/api.tsp, lib/core/lib/core/fields/file.tsp, lib/core/lib/core/models/application.tsp, lib/core/lib/core/models/competition.tsp, lib/core/lib/core/models/form.tsp, lib/core/lib/core/routes/applications.tsp, lib/core/lib/core/routes/forms.tsp, lib/core/lib/main.tsp
Prepares core library for a v0.3.0 pre-release by fixing a few missing fields and adding support for fetching applications.
- Fixes #317 
- Time to review: 20 minutes
- Creates a new `v0.3.0` version to manage new routes and fields
- Adds `POST /applications/search/` following the pattern established by `POST /opportunities/search/`
- Adds `opportunityId` to `ApplicationBase`
- Renames `Form` --> `FormBase` to align with other base models that have `customFields` 
- Adds `version` to `FormBase` to align with SGG apply pilot
- Adds examples to Application for file attachments
> Testing instructions, background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers. Explain how the …
=> [Issue #317] Support fetching apps in core library
